language: node_js
env:
  global:
  - CC_TEST_REPORTER_ID=335060ad6bc0ba88d43e0706a39b7c924c3e39cc68d0de0a3a4b23ff509e6778
  - $GITHUB_API_KEY=pS8dIFfzPofroH3WHCJJFk8VRKXXLiPd39NGMZre48XHMAo5O+FBB4xlILyM/8krhbG31zzbUKozfcMgcAT/FSC4kDgYCBvCHwdK/h1huLex2+dbkwjGeXe71AeDAu7HgAplRz50XyhCpqEyUYf0JRa+hzi0y8qdL5AKz8GgcuQlVTMK4zePDOAzIODeaig+/6HrZ9wyOg8yZbk/bioBh4NmmfF4USUCeK22yWIDJ8+82w0X7Fa7Cr/htAj7spb+z6c3H32QwFtIqGqp03D4MgzwAVKzPPw7NKMBZzFeuZLMg3SKtC6R9ZgM5fmUTlfrE34rkCWI4APljnU9vZqGsXBktPmfvUdxSyO+rOkJaRpJazs9HQZbvn3aj/nN80VF4sKaB71UYT9VPPOENq3KmYI7B9tRjlUNmdjQl13uSnsFf/MULbDYXVCCm17+QuOyJ4tNuxDYV7gcLFn/VSW8qu0TrTJhCKe98w786CE2E/aK0151efxPjp75KqmAoB28ZQIlP2yq6F9FPdgV+KK1oXiF+GSMpG6QIrXEoBMp/VkalYEpqRp8ef78IBJ5iOUnf+X4OvYu5VXqC+QFp0L9TKS9lVqm7oZj80Db/rOhSqbUWJB7vkFVq4otXFTDmtWauA9iXhTcevCL4x6zW7bSd6r4awKD669J/yQF7cwHkMI=
node_js:
- node
cache: yarn
deploy:
  provider: pages
  local-dir: doc
  skip-cleanup: true
  github-token: "$GITHUB_API_KEY"
  keep-history: true
  on:
    branch: master
before_install:
- pip install --user codecov
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
after_success:
- yarn doc
- codecov --file coverage/lcov.info --disable search
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
